
modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"

[[mods]] #mandatory
modId = "seasontweaks" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "SeasonTweaks" #mandatory
authors = "iananderson" #optional

description = '''
Tweaks for Serene Seasons
'''
[[dependencies.seasontweaks]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.seasontweaks]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2,1.19)"
ordering = "NONE"
side = "BOTH"

[[dependencies.seasontweaks]]
modId = "sereneseasons"
mandatory = true
versionRange = "[1.18.2-7.0.0.13,)"
ordering = "AFTER"
side = "BOTH"